
import { GoogleGenAI } from "@google/genai";
import { Experiment, Protocol, Language, ExperimentInsight, PaperAnalysis, EvidenceGrading } from "../types";

// Função auxiliar para criar uma análise simulada realista (Fallback)
const getMockInsight = (experiment: Experiment, protocol: Protocol, lang: Language): ExperimentInsight => {
    const isPt = lang === 'pt';
    const logs = [...experiment.baselineLogs, ...experiment.interventionLogs];
    const avg = logs.reduce((a, b) => a + b.metricValue, 0) / (logs.length || 1);
    
    return {
        headline: isPt ? "Protocolo Concluído com Sucesso" : "Protocol Successfully Completed",
        trendDirection: avg > 5 ? "POSITIVE" : "NEUTRAL",
        statisticalSummary: isPt 
            ? `Com base em ${logs.length} registros, sua média de desempenho foi ${avg.toFixed(1)}/10. O sistema detectou consistência na execução.`
            : `Based on ${logs.length} logs, your average performance was ${avg.toFixed(1)}/10. The system detected consistency in execution.`,
        observation: isPt
            ? "Você demonstrou boa aderência ao protocolo. Fatores externos podem ter influenciado nos dias de menor pontuação."
            : "You demonstrated good adherence to the protocol. External factors may have influenced lower scoring days.",
        recommendation: isPt
            ? "Recomendamos continuar com este protocolo por mais 7 dias para consolidar o hábito."
            : "We recommend continuing this protocol for another 7 days to consolidate the habit.",
        disclaimer: isPt
            ? "Gerado pelo Modo de Simulação LoredoLAB (Chave API não detectada ou erro de rede)."
            : "Generated by LoredoLAB Simulation Mode (API Key not detected or network error)."
    };
};

export const generateExperimentInsight = async (
  experiment: Experiment,
  protocol: Protocol,
  lang: Language = 'en'
): Promise<ExperimentInsight | null> => {
  try {
    // Verificar se a chave existe antes de tentar chamar
    const apiKey = process.env.API_KEY;
    
    if (!apiKey || apiKey.includes("PLACEHOLDER") || apiKey === "") {
        console.warn("⚠️ API Key not found. Using Simulation Mode.");
        // Simular um delay de "pensamento" para UX
        await new Promise(resolve => setTimeout(resolve, 2000));
        return getMockInsight(experiment, protocol, lang);
    }

    const ai = new GoogleGenAI({ apiKey: apiKey });

    const baselineAvg = experiment.baselineLogs.length > 0 
      ? (experiment.baselineLogs.reduce((acc, log) => acc + log.metricValue, 0) / experiment.baselineLogs.length).toFixed(2)
      : '0';
    
    const interventionAvg = experiment.interventionLogs.length > 0
      ? (experiment.interventionLogs.reduce((acc, log) => acc + log.metricValue, 0) / experiment.interventionLogs.length).toFixed(2)
      : '0';

    const langInstruction = lang === 'pt' 
      ? "Output language: Portuguese (pt-BR)." 
      : "Output language: English.";

    const prompt = `
      Analyze this N=1 productivity experiment.
      Protocol: ${protocol.title} (${protocol.mechanism})
      
      Data:
      - Baseline Avg (1-10): ${baselineAvg} (Count: ${experiment.baselineLogs.length})
      - Intervention Avg (1-10): ${interventionAvg} (Count: ${experiment.interventionLogs.length})
      
      Notes Sample: ${experiment.interventionLogs.slice(0, 3).map(l => l.notes).join(' | ')}
    `;

    const systemInstruction = `
      You are a Senior Data Scientist at a Productivity Lab.
      ${langInstruction}
      
      Rules:
      1. Be conservative. This is N=1 self-reported data.
      2. If the difference is < 0.5, consider it NEUTRAL/Inconclusive.
      3. DO NOT make medical diagnoses. Use terms like "suggests", "appears to", "correlated with".
      4. Check the notes for confounders (e.g., "was sick", "bad sleep").
      5. Keep the disclaimer standard: "This is a personal experiment, not clinical evidence."
    `;

    // --- SCHEMA DEF ---
    const insightSchema = {
      type: "OBJECT",
      properties: {
        headline: { type: "STRING", description: "A short, catchy summary of the result (max 10 words)." },
        trendDirection: { type: "STRING", enum: ["POSITIVE", "NEGATIVE", "NEUTRAL"] },
        statisticalSummary: { type: "STRING", description: "Data-driven comparison of baseline vs intervention averages." },
        observation: { type: "STRING", description: "Qualitative analysis of user notes and consistency." },
        recommendation: { type: "STRING", description: "Actionable advice: Continue, Modify, or Stop." },
        disclaimer: { type: "STRING", description: "Standard limitation warning (N=1, not medical advice)." }
      },
      required: ["headline", "trendDirection", "statisticalSummary", "observation", "recommendation", "disclaimer"]
    };

    const response = await ai.models.generateContent({
      model: 'gemini-3-flash-preview',
      contents: prompt,
      config: {
        responseMimeType: "application/json",
        responseSchema: insightSchema,
        systemInstruction: systemInstruction,
      },
    });

    const text = response.text;
    if (!text) throw new Error("Empty response from AI");
    
    return JSON.parse(text) as ExperimentInsight;

  } catch (error) {
    console.error("Gemini AI Insight Failed (Falling back to Simulation):", error);
    // Em caso de erro real (ex: quota exceeded), também retornamos o mock para não quebrar a UX
    return getMockInsight(experiment, protocol, lang);
  }
};

export const analyzeScientificPaper = async (abstractOrText: string, lang: Language = 'en'): Promise<PaperAnalysis | null> => {
    return null; // Placeholder
};

export const gradeProtocolEvidence = async (protocolDescription: string, citations: string[], lang: Language = 'en'): Promise<EvidenceGrading | null> => {
    return null; // Placeholder
};
